### ISSUE TITLE
SwaggerAPIを用いた外部ドキュメントとwell-typedなコードの両立

### ISSUE THREAD

**Issue by KisaragiEffective** [GiganticMinecraft/SeichiRankingBFF#9]

**Comment by inductor** [comment]
https://docs.rs/openapi/latest/openapi/ とか？

**Comment by kory33** [comment]
実はwell-typedなコードとの両立はできていないです(OpenAPIによる定義とRust上のpresentation modelが一致している保証が取れていない)

**Comment by kory33** [comment]
現状OpenAPI 3.0でのデータ型の定義からRustのstructやserdeシリアライザ実装を生成できるコードジェネレータが無いので、無理そう

**Comment by kory33** [comment]
wontfixですね
